# Generated by Django 2.2.2 on 2020-03-13 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendor_process.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(unique=True)),
                ('acc_holder_name', models.CharField(max_length=100)),
                ('acc_holder_contact_no', models.IntegerField()),
                ('status', models.CharField(default=None, max_length=9, null=True)),
                ('created_date', models.DateTimeField()),
                ('update_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vendor_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(default=vendor_process.models.increment_vendor_number, editable=False, max_length=20)),
                ('company_nick_name', models.CharField(max_length=254)),
                ('company_name_reg', models.CharField(max_length=254)),
                ('door_street', models.CharField(max_length=254)),
                ('locality', models.CharField(max_length=254, null=True)),
                ('state', models.CharField(max_length=254, null=True)),
                ('pincode', models.IntegerField()),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_contact_name', models.CharField(max_length=100, null=True)),
                ('primary_contact_no', models.BigIntegerField(default=0, null=True)),
                ('secondary_email', models.EmailField(max_length=254, null=True)),
                ('secondary_contact_no', models.BigIntegerField(default=0, null=True)),
                ('secondary_contact_name', models.CharField(max_length=254, null=True)),
                ('gstin', models.CharField(max_length=15, null=True)),
                ('uin', models.CharField(blank=True, max_length=15, null=True)),
                ('insurance_no', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=254, null=True)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(default=None, max_length=9, null=True)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('door_street', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('locality', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, default=None, null=True)),
                ('contact_no', models.IntegerField(blank=True, default=None, null=True)),
                ('gstin', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('uin', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('insurance_no', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('insurance_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, default=None, null=True)),
                ('addr_identity', models.CharField(max_length=15)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='vendor_process.user_info', to_field='account_id')),
            ],
        ),
    ]
