# Generated by Django 2.2.2 on 2020-03-13 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_process', '0002_auto_20200313_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_information',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
