# Generated by Django 2.2.2 on 2020-03-13 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_process', '0003_auto_20200313_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_information',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
