# Generated by Django 2.2.2 on 2020-03-18 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_process', '0004_auto_20200313_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='account_id',
            field=models.ForeignKey(db_column='account_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
