# Generated by Django 2.2.2 on 2020-03-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_process', '0005_auto_20200318_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'state',
            },
        ),
    ]
