# Generated by Django 2.2.2 on 2020-04-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_process', '0006_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='acc_holder_contact_no',
            field=models.BigIntegerField(),
        ),
    ]
