# Generated by Django 2.2.2 on 2020-04-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_process', '0007_auto_20200401_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_address',
            name='contact_no',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
