# Generated by Django 3.0.2 on 2020-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trade_information',
            fields=[
                ('bussiness_mode', models.CharField(max_length=30)),
                ('conf_no', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('conf_date', models.DateTimeField()),
                ('buyer_name', models.CharField(max_length=25)),
                ('gstin_buyer', models.CharField(max_length=10)),
                ('buyer_door_street', models.CharField(max_length=100)),
                ('buyer_state', models.CharField(max_length=50)),
                ('buyer_pincode', models.IntegerField()),
                ('seller_name', models.CharField(max_length=25)),
                ('gstin_seller', models.CharField(max_length=10)),
                ('trader_name', models.CharField(max_length=50)),
                ('trader_type', models.CharField(max_length=15)),
                ('broker_name', models.CharField(max_length=50)),
                ('broker_contact_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('broker_email', models.EmailField(max_length=254)),
                ('broker_commission_percent', models.BigIntegerField(blank=True, default=None, null=True)),
                ('broker_commission_rupees', models.BigIntegerField(blank=True, default=None, null=True)),
                ('station', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=50)),
                ('hsn_code', models.IntegerField()),
                ('variety', models.CharField(max_length=15)),
                ('staple_buyer', models.IntegerField()),
                ('staple_seller', models.IntegerField()),
                ('mic_buyer', models.IntegerField()),
                ('mic_seller', models.IntegerField()),
                ('grade', models.CharField(max_length=15)),
                ('gtex_buyer', models.IntegerField(blank=True, default=None)),
                ('gtex_seller', models.IntegerField(blank=True, default=None)),
                ('gpt', models.IntegerField(blank=True)),
                ('moist_buyer', models.IntegerField()),
                ('moist_seller', models.IntegerField()),
                ('trash_buyer', models.IntegerField()),
                ('trash_seller', models.IntegerField()),
                ('bales_nos', models.IntegerField()),
                ('truck_nos', models.IntegerField()),
                ('price', models.IntegerField()),
                ('delivery_terms', models.CharField(max_length=10)),
                ('gst', models.IntegerField()),
                ('dispatch_terms', models.CharField(max_length=30)),
                ('payment_terms', models.CharField(max_length=50)),
                ('first_payment', models.IntegerField(blank=True)),
                ('first_payment_days', models.IntegerField(blank=True)),
                ('second_payment', models.IntegerField(blank=True)),
                ('second_payment_days', models.IntegerField(blank=True)),
                ('dhara', models.CharField(blank=True, max_length=50)),
                ('gst_payment', models.CharField(max_length=50)),
                ('interest_late_payment', models.IntegerField()),
                ('weighment_terms', models.CharField(max_length=30)),
                ('passing_terms', models.CharField(max_length=30)),
                ('transit_insurance_details', models.CharField(max_length=100)),
                ('unloading_contact_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('weighbridge_contact_no', models.BigIntegerField(blank=True, default=None, null=True)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
