# Generated by Django 2.2.2 on 2020-03-20 15:25

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='logged_in_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
