# Generated by Django 2.2.2 on 2020-04-01 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_login', '0002_loggedinuser_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
